version: "3.8"

services:
  dotnetapp:
    image: mcr.microsoft.com/dotnet/samples:dotnetapp
    ports:
      - "80:80"  
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
